sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: SMHsmh12!
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
